apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-canary
  namespace: test-app
spec:
  replicas: 1              # 전체 5개 중 1개 (20%)
  selector:
    matchLabels:
      app: nestjs
      version: canary
  template:
    metadata:
      labels:
        app: nestjs
        version: canary
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: nestjs
        # deploy-canary.yml 이 이 부분을 업데이트
        image: 923516172483.dkr.ecr.ap-northeast-2.amazonaws.com/nestjs-app:aca3b416fa83f66159716a2c4b96e30e5f1b8d9f
        ports:
        - containerPort: 3000
