apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-stable
  namespace: test-app
spec:
  replicas: 2              # 전체 5개 중 4개 (80%)
  selector:
    matchLabels:
      app: nestjs
      version: stable
  template:
    metadata:
      labels:
        app: nestjs
        version: stable
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: nestjs
        # 현재 운영중인 이미지 태그 그대로 유지
        image: 923516172483.dkr.ecr.ap-northeast-2.amazonaws.com/nestjs-app:0b7d4fcd2fe2ceae47dd7bcccee661c6520ac92f
        ports:
        - containerPort: 3000
        resources:          # ← 추가할 위치
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
