apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs
  namespace: test-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: nestjs
        image: 923516172483.dkr.ecr.ap-northeast-2.amazonaws.com/nestjs-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nestjs
  namespace: test-app
spec:
  type: NodePort
  selector:
    app: nestjs
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 32079
